import { escapeHtml } from './dom.js';
import type { Player } from '../types.js';
import { network } from './network.js';
import { ELEMENT_BY_ID } from '../data/content.js';
const esc = escapeHtml;
const button = (label: string, action: string, id = '', disabled = false) => '<button class="button secondary" data-action="net-' + action + '" data-id="' + esc(id) + '" ' + (disabled ? 'disabled' : '') + '>' + label + '</button>';
export function renderCommunity(player: Player) {
  const head = '<div class="page-heading"><div><div class="eyebrow">KNOWLEDGE GROWS WHEN IT IS SHARED</div><h1>The Alchemists’ Assembly</h1><p>Meet other alchemists, test formations, and pursue discoveries together.</p></div></div>';
  if (!network.account) return head + '<section class="panel content-panel account-panel"><h2>A journal beyond this device</h2><p>Online accounts have their own server-validated progression. Your local journal stays on this device and returns when you sign out.</p>' + (!network.available ? '<p class="note">The shared-world service is not available on this host. Run the included Node server to enable accounts and community play.</p>' : '') + '<form id="account-form"><label>Alchemist name<input id="account-name" autocomplete="username" minlength="3" maxlength="24" required placeholder="Your public alchemist name"></label><label>Password<input id="account-password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><div class="button-row">' + button('Sign in', 'login') + button('Create account', 'register') + '</div></form><p class="subtle">Use 3–24 letters, numbers, underscores or hyphens for your public name, and at least 12 characters for your password.</p></section>';
  const world = network.world;
  if (!world) return head + '<section class="panel content-panel"><p>Signed in as ' + esc(network.account.name) + '.</p>' + button('Load the shared world', 'refresh') + button('Sign out', 'logout') + '</section>';
  const guild = world.guilds.find(g => g.id === world.self.guildId);
  const names = Object.fromEntries(world.players.map(p => [p.id, p.name]));
  return head + '<div class="resource-banner"><span>' + esc(world.self.name) + '</span><span>Rating ' + world.self.rating + '</span><span>Season ' + world.rotation.season + '</span>' + button('Refresh', 'refresh') + button('Sign out', 'logout') + '</div>'
    + (world.live.announcements.length ? '<section class="panel content-panel"><h2>' + esc(world.live.seasonName || world.rotation.seasonName) + '</h2>' + world.live.announcements.map(a => '<p>' + esc(a) + '</p>').join('') + '</section>' : '')
    + '<h2>Alchemists & the arena</h2><label>Draft arena · choose three of today’s six elements<select id="arena-draft" multiple size="6">' + world.rotation.draft.map(id => '<option value="' + id + '">' + ELEMENT_BY_ID[id].name + '</option>').join('') + '</select></label><p class="subtle">Ranked battles normalize mastery, evolution, research and talents. Your composition, equipment and reaction choices remain meaningful. Rewards and rating apply once per opponent each UTC day.</p><div class="table-scroll"><table class="world-table"><thead><tr><th>Alchemist</th><th>Rating</th><th>Discoveries</th><th>Endless</th><th>Actions</th></tr></thead><tbody>' + world.players.map(p => '<tr><td>' + esc(p.name) + (world.friends.includes(p.id) ? ' · Friend' : '') + '</td><td>' + p.rating + '</td><td>' + p.discoveries + '</td><td>' + p.endlessBest + '</td><td>' + (p.id === world.self.id ? 'You' : button('Challenge', 'duel', p.id) + button('Draft duel', 'draft-duel', p.id) + (world.self.guildId && p.guildId && p.guildId !== world.self.guildId ? button('Guild war', 'war', p.id) : '') + (world.requests.includes(p.id) ? button('Accept friend', 'friend-accept', p.id) : !world.friends.includes(p.id) ? button('Add friend', 'friend-request', p.id) : '')) + '</td></tr>').join('') + '</tbody></table></div>'
    + '<h2 class="spaced-heading">A shared pursuit</h2>' + (guild ? '<section class="panel content-panel"><div class="eyebrow">YOUR GUILD</div><h2>' + esc(guild.name) + '</h2><p>' + guild.members.length + ' members · ' + guild.knowledge + ' pooled knowledge · research tier ' + guild.research + ' · ' + guild.discoveries.length + ' shared discoveries</p><p>Weekly guardian: ' + guild.raid.health.toLocaleString() + ' shared health remaining. Each member contributes one battle per week.</p><div class="button-row">' + button('Donate 5 knowledge', 'guild-donate') + button('Challenge guild guardian', 'raid', '', guild.raid.claims.includes(world.self.id)) + button('Claim guild milestone', 'guild-reward') + button('Leave guild', 'guild-leave') + '</div><label>Contribute a discovery<select id="guild-discovery"><option value="">Choose a known reaction</option>' + player.discoveries.map(id => '<option value="' + id + '">' + ELEMENT_BY_ID[id].name + '</option>').join('') + '</select></label>' + button('Contribute to laboratory', 'guild-discovery') + '<h3 class="spaced-heading">Members</h3><p>' + guild.members.map(id => esc(names[id] ?? 'Alchemist')).join(', ') + '</p></section>' : '<div class="two-column"><section class="panel content-panel"><h2>Start a guild</h2><label>Guild name<input id="guild-name" maxlength="40" placeholder="The Curious Few"></label>' + button('Create guild', 'guild-create') + '</section><section class="panel content-panel"><h2>Find your people</h2>' + (world.guilds.length ? world.guilds.map(g => '<div class="community-row"><span>' + esc(g.name) + ' · ' + g.members.length + ' members</span>' + button('Join', 'guild-join', g.id) + '</div>').join('') : '<p>No guilds have been founded yet.</p>') + '</section></div>')
    + '<h2 class="spaced-heading">Weekly guild standings</h2><section class="panel content-panel">' + [...world.guilds].sort((a, b) => (b.war?.week === world.rotation.week ? b.war.score : 0) - (a.war?.week === world.rotation.week ? a.war.score : 0)).map(g => '<p>' + esc(g.name) + ' · ' + (g.war?.week === world.rotation.week ? g.war.score : 0) + ' points</p>').join('') + '<p class="subtle">Challenge a rival guild member. A victory earns 3 points and a draw 1, once per opponent per member each week.</p></section>'
    + '<h2 class="spaced-heading">Discovery sharing</h2><section class="panel content-panel"><p>Shared recipes stay hidden until you choose to reveal them. Revealing a recipe does not add it to your codex; the experiment is still yours to perform.</p><div class="form-row"><label>Your discovery<select id="share-reaction">' + player.discoveries.map(id => '<option value="' + id + '">' + ELEMENT_BY_ID[id].name + '</option>').join('') + '</select></label>' + button('Share discovery', 'share-discovery', '', !player.discoveries.length) + '</div>' + world.shares.map(s => '<div class="community-row"><span>' + esc(s.author) + ' shared a discovery.</span>' + button('Reveal recipe', 'reveal-share', s.id) + '</div>').join('') + '</section>'
    + '<h2 class="spaced-heading">Questions for other minds</h2><div class="two-column"><section class="panel content-panel"><h2>Create an experiment challenge</h2><label>Challenge name<input id="challenge-name" maxlength="40" placeholder="A storm from a spark"></label><label>Target reaction<select id="challenge-target">' + player.discoveries.map(id => '<option value="' + id + '">' + ELEMENT_BY_ID[id].name + '</option>').join('') + '</select></label><label>Starting elements (choose two to six)<select id="challenge-allowed" multiple size="6">' + player.owned.map(id => '<option value="' + id + '">' + ELEMENT_BY_ID[id].name + '</option>').join('') + '</select></label>' + button('Publish challenge', 'challenge-create', '', !player.discoveries.length) + '</section><section class="panel content-panel"><h2>Community challenges</h2>' + (world.challenges.length ? world.challenges.map(c => '<article class="challenge-entry"><h3>' + esc(c.name) + '</h3><p>By ' + esc(c.author) + ' · Create ' + esc(c.targetName) + '<br>Allowed: ' + c.allowed.map(id => ELEMENT_BY_ID[id].name).join(', ') + '</p>' + button(c.solved ? 'Solved' : 'Solve challenge', 'solve-dialog', c.id, c.solved) + '</article>').join('') : '<p>Publish the first question for another alchemist to solve.</p>') + '</section></div>';
}
