import { challengeDefinition } from '../core/challenges.js';
import { ELEMENT_BY_ID, VESSELS, VESSEL_BY_ID, ENCOUNTERS, REACTIONS } from '../data/content.js';
import { TALENTS, EQUIPMENT, PASSIVES, SPECIALIZATIONS, QUESTS, ACHIEVEMENTS, RUN_UPGRADES, MUTATORS, COSMETICS } from '../data/systems.js';
import { availableVessels, evolutionCost, questProgress, analyticsReport } from '../core/meta.js';
import { rotation, runEncounter } from '../core/modes.js';
import { icon } from './art.js';

const esc = v => String(v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const btn = (label, action, extra = '', disabled = false) => '<button class="button secondary" data-action="x-' + action + '" ' + extra + (disabled ? ' disabled' : '') + '>' + label + '</button>';
const options = (ids, selected) => ids.map(id => '<option value="' + id + '" ' + (selected === id ? 'selected' : '') + '>' + ELEMENT_BY_ID[id].name + '</option>').join('');
const heading = (title, description) => '<div class="page-heading"><div><div class="eyebrow">THE WORK OF AN ALCHEMIST</div><h1>' + title + '</h1><p>' + description + '</p></div></div>';

export function renderWorkshop(player) {
  return heading('The Artificer’s Workshop', 'Craft tools, refine elements, and shape the way your formation fights.')
    + '<div class="resource-banner"><span>' + player.gold + ' gold</span><span>' + player.essence + ' essence</span><span>' + player.shards + ' relic shards</span><span>' + player.knowledge + ' knowledge</span></div>'
    + '<div class="button-row spaced-heading">' + btn('Craft all affordable tools', 'craft-all') + '</div>'
    + '<h2>Tools with a purpose</h2><div class="research-grid">' + EQUIPMENT.map(e => '<article class="panel content-panel"><div class="eyebrow">' + e.slot + ' · ' + e.rarity + '</div><h2>' + e.name + '</h2><p>' + e.description + '</p><p class="subtle">' + e.gold + ' gold · ' + e.essence + ' essence · ' + e.shards + ' shards</p>' + btn(player.equipment.includes(e.id) ? 'Crafted' : 'Craft ' + e.name, 'craft', 'data-id="' + e.id + '"', player.equipment.includes(e.id) || player.gold < e.gold || player.essence < e.essence || player.shards < e.shards) + '</article>').join('') + '</div>'
    + '<section class="panel content-panel workshop-evolution"><h2>Change what an element can become.</h2><p>Evolution I extends statuses. Evolution II adds splash damage. Evolution III grants a protective opening ward. Specialization changes behavior, and can be switched freely.</p><div class="form-row"><label>Element<select id="evolution-element">' + options(player.owned) + '</select></label><label>Specialization<select id="specialization">' + SPECIALIZATIONS.map(s => '<option value="' + s.id + '">' + s.name + '</option>').join('') + '</select></label></div><div class="button-row">' + btn('Evolve selected element', 'evolve') + btn('Set specialization', 'specialize') + '</div><p class="subtle">Evolution costs 60/120/180 gold and 15/30/45 essence, with 15/30/45 mastery XP. Current evolutions: ' + (Object.entries(player.evolution).map(([id, n]) => ELEMENT_BY_ID[id].name + ' ' + n).join(', ') || 'none') + '.</p><ul class="plain-list">' + SPECIALIZATIONS.map(s => '<li><strong>' + s.name + ':</strong> ' + s.description + '</li>').join('') + '</ul></section>'
    + '<h2>Paths of study</h2><div class="research-grid">' + TALENTS.map(t => '<article class="panel content-panel"><div class="eyebrow">' + t.branch + '</div><h2>' + t.name + '</h2><p>' + t.description + '</p>' + (t.requires ? '<p class="subtle">Requires ' + TALENTS.find(x => x.id === t.requires).name + '</p>' : '') + btn(player.talents.includes(t.id) ? 'Learned' : 'Learn · ' + t.cost + ' knowledge', 'talent', 'data-id="' + t.id + '"', player.talents.includes(t.id) || player.knowledge < t.cost || t.requires && !player.talents.includes(t.requires)) + '</article>').join('') + '</div>'
    + '<h2 class="spaced-heading">A laboratory of your own</h2><div class="research-grid">' + COSMETICS.map(c => '<article class="panel content-panel"><h2 style="color:' + c.color + '">' + c.name + '</h2><p>A cosmetic laboratory palette.</p>' + btn(player.theme === c.id ? 'Selected' : player.cosmetics.includes(c.id) ? 'Apply theme' : c.cost + ' gold', 'cosmetic', 'data-id="' + c.id + '"', player.theme === c.id) + '</article>').join('') + '</div>';
}

export function renderFormationTools(player) {
  return '<section class="panel content-panel spaced-heading"><h2>Vessels, passives & equipment</h2><p>New vessels unlock through victories. Passives unlock through discoveries. Every vessel is a home for your elements.</p><div class="advanced-formation">' + player.team.map((slot, i) => '<article><h3>Position ' + (i + 1) + ' · ' + VESSEL_BY_ID[slot.vessel].name + '</h3><label>Vessel<select data-x-select="vessel" data-index="' + i + '">' + availableVessels(player).map(v => '<option value="' + v.id + '" ' + (slot.vessel === v.id ? 'selected' : '') + ' ' + (player.team.some((s, n) => n !== i && s.vessel === v.id) ? 'disabled' : '') + '>' + v.name + '</option>').join('') + '</select></label><label>Passive<select data-x-select="passive" data-index="' + i + '">' + PASSIVES.filter(p => p.unlockDiscoveries <= player.discoveries.length).map(p => '<option value="' + p.id + '" ' + ((slot.passive ?? 'none') === p.id ? 'selected' : '') + '>' + p.name + '</option>').join('') + '</select></label><p class="subtle">' + (PASSIVES.find(p => p.id === slot.passive)?.description ?? 'Choose a passive triggered by combat events.') + '</p><label>Crafted equipment<select data-x-select="equip" data-index="' + i + '"><option value="">Choose a crafted item</option>' + EQUIPMENT.filter(e => player.equipment.includes(e.id)).map(e => '<option value="' + e.id + '">' + e.name + ' (' + e.slot + ')</option>').join('') + '</select></label><p class="subtle">Equipped: ' + (Object.values(slot.equipment ?? {}).map(id => EQUIPMENT.find(e => e.id === id)?.name).join(', ') || 'none') + '</p>' + [0, 1, 2].map(rank => '<label>Reaction priority ' + (rank + 1) + '<select data-x-select="reaction-priority" data-rank="' + rank + '" data-index="' + i + '"><option value="">Automatic</option>' + player.discoveries.map(id => '<option value="' + id + '" ' + (slot.reactionPriority?.[rank] === id ? 'selected' : '') + '>' + ELEMENT_BY_ID[id].name + '</option>').join('') + '</select></label>').join('') + '</article>').join('') + '</div><div class="form-row"><label>Save this formation<input id="loadout-name" maxlength="40" placeholder="Storm garden"></label>' + btn('Save formation', 'save-loadout') + '</div><div class="button-row">' + player.loadouts.map((l, i) => btn('Load ' + esc(l.name), 'apply-loadout', 'data-index="' + i + '"')).join('') + '</div></section>';
}

export function renderJournal(player) {
  const current = rotation();
  return heading('Your Field Journal', 'A record of questions, milestones, and the things you are beginning to understand.')
    + '<section class="panel content-panel"><div class="eyebrow">' + current.seasonName + ' · ' + current.season + '</div><h2>This week: ' + current.mutator.name + '</h2><p>' + current.mutator.description + ' Enter Infinite Alchemy to explore the changing rules.</p><a class="text-link" href="#runs">Enter the Unwritten Path →</a><h3>Daily experiment · ' + current.day + ' (UTC)</h3><p>' + current.puzzle.hint + '</p>' + btn(player.dailyClaims.includes('puzzle:' + current.day) ? 'Reward claimed' : 'Claim daily discovery reward', 'daily', '', player.dailyClaims.includes('puzzle:' + current.day) || !player.discoveries.includes(current.puzzle.id)) + '</section>'
    + '<div class="research-grid spaced-heading">' + ['daily', 'weekly', 'festival'].map(kind => { const d = challengeDefinition(kind); return '<article class="panel content-panel"><h2>' + d.name + '</h2><p>' + d.description + '</p><p>' + d.gold + ' gold · ' + d.knowledge + ' knowledge · ' + d.essence + ' essence</p>' + btn(player.dailyClaims.includes(d.key) ? 'Completed this period' : 'Enter trial', 'trial', 'data-id="' + kind + '"', player.dailyClaims.includes(d.key)) + '</article>'; }).join('') + '</div><div class="button-row spaced-heading">' + btn('Claim completed quests', 'claim-all') + '</div>'
    + '<h2 class="spaced-heading">Questions worth pursuing</h2><div class="research-grid">' + QUESTS.map(q => '<article class="panel content-panel"><h2>' + q.name + '</h2><p>' + q.description + '</p><div class="meter"><i style="width:' + Math.min(100, questProgress(player, q) / q.target * 100) + '%"></i></div><p class="subtle">' + Math.min(q.target, questProgress(player, q)) + ' / ' + q.target + ' · ' + q.gold + ' gold · ' + q.knowledge + ' knowledge</p>' + btn(player.quests.includes(q.id) ? 'Completed' : 'Claim reward', 'quest', 'data-id="' + q.id + '"', player.quests.includes(q.id) || questProgress(player, q) < q.target) + '</article>').join('') + '</div>'
    + '<h2 class="spaced-heading">Your alchemical identity</h2><div class="stat-grid"><div class="panel stat"><span>Highest reaction chain</span><strong>' + player.highestChain + '</strong></div><div class="panel stat"><span>Runs completed</span><strong>' + player.runsWon + '</strong></div><div class="panel stat"><span>Deepest endless floor</span><strong>' + player.endlessBest + '</strong></div></div><div class="stat-grid"><div class="panel stat"><span>Rare discoveries</span><strong>' + player.discoveries.filter(id => ['Rare', 'Epic', 'Legendary'].includes(ELEMENT_BY_ID[id].rarity)).length + '</strong></div><div class="panel stat"><span>Mastered elements</span><strong>' + Object.values(player.mastery).filter(n => n >= 90).length + '</strong></div><div class="panel stat"><span>Favorite element</span><strong class="profile-word">' + (ELEMENT_BY_ID[player.favorites[0]]?.name ?? 'Undecided') + '</strong></div></div><div class="achievement-list">' + ACHIEVEMENTS.map(a => '<div class="panel achievement ' + (player.achievements.includes(a.id) ? 'earned' : '') + '">' + icon(player.achievements.includes(a.id) ? 'star' : 'lock') + '<span><strong>' + a.name + '</strong><small>' + a.description + '</small></span></div>').join('') + '</div>'
    + '<details class="panel content-panel spaced-heading"><summary>Recovered memories · ' + player.campaign.length + '</summary>' + ENCOUNTERS.filter(e => player.campaign.includes(e.id)).map(e => '<article><h3>' + e.region + ' · ' + e.name + '</h3><p>' + e.description + '</p></article>').join('') + '</details>'
    + '<details class="panel content-panel spaced-heading"><summary>Local discovery analytics</summary><p class="subtle">These events remain in this journal. Online accounts store their own gameplay events on your server.</p><pre class="data-preview">' + esc(JSON.stringify(analyticsReport(player), null, 2)) + '</pre></details>';
}

export function renderRuns(player) {
  const run = player.run, current = rotation();
  if (!run || ['complete', 'defeat', 'retired'].includes(run.state)) return heading('The Unwritten Path', 'A fresh set of elements. A different theory. A world that changes with every run.')
    + (run ? '<section class="panel content-panel"><h2>' + (run.state === 'complete' ? 'A remarkable journey.' : run.state === 'defeat' ? 'A lesson from the depths.' : 'Your discoveries return with you.') + '</h2><p>' + run.wins + ' victories · ' + run.discoveries.length + ' reactions learned · ' + run.wins * 20 + ' gold · ' + run.wins * 5 + ' essence. Rewards have been added to your journal.</p></section>' : '')
    + '<div class="research-grid spaced-heading">' + [['roguelite', 'The Unwritten Path', 'Eight encounters, a reward draft after each victory, and two guardians. Health carries between battles.'], ['endless', 'The Infinite Dungeon', 'Descend until your formation falls. Enemies grow stronger each floor.'], ['infinite-alchemy', 'Infinite Alchemy', 'An endless descent with this week’s rule: ' + current.mutator.description], ['draft', 'Element Draft', 'Build a run from today’s limited pool: ' + current.draft.map(id => ELEMENT_BY_ID[id].name).join(', ') + '.']].map(([id, title, description]) => '<article class="panel content-panel"><div class="eyebrow">' + id + '</div><h2>' + title + '</h2><p>' + description + '</p><label>First element<select id="start-a-' + id + '">' + options(id === 'draft' ? current.draft : player.owned.filter(id => ELEMENT_BY_ID[id].base && !ELEMENT_BY_ID[id].unlockResearch)) + '</select></label><label>Second element<select id="start-b-' + id + '">' + options(id === 'draft' ? current.draft : player.owned.filter(id => ELEMENT_BY_ID[id].base && !ELEMENT_BY_ID[id].unlockResearch), id === 'draft' ? current.draft[1] : 'water') + '</select></label>' + btn('Begin ' + title, 'start-run', 'data-mode="' + id + '"') + '</article>').join('') + '</div>';
  const encounter = runEncounter(run);
  return heading('Floor ' + run.floor + ' · ' + encounter.name, 'Your expedition is saved automatically. Your formation’s health carries forward.')
    + '<div class="resource-banner"><span>' + run.mode + '</span><span>' + run.wins + ' victories</span><span>' + MUTATORS.find(m => m.id === run.mutator).name + '</span><span>' + run.upgrades.length + ' upgrades</span></div>'
    + (run.state === 'reward' ? '<h2>What will you bring with you?</h2><div class="research-grid">' + run.rewards.map((r, i) => '<article class="panel content-panel"><div class="eyebrow">' + r.type + '</div><h2>' + (r.type === 'element' ? ELEMENT_BY_ID[r.id].name : r.type === 'upgrade' ? RUN_UPGRADES.find(u => u.id === r.id).name : 'A Moment of Rest') + '</h2><p>' + (r.type === 'element' ? 'Add this element to your temporary collection.' : r.type === 'upgrade' ? RUN_UPGRADES.find(u => u.id === r.id).description : 'Heal the party by 35% and revive fallen vessels at 60%.') + '</p>' + btn('Choose reward', 'run-reward', 'data-index="' + i + '"') + '</article>').join('') + '</div>' : '<section class="panel content-panel"><div class="eyebrow">' + encounter.environment + ' · ' + (encounter.boss ? 'GUARDIAN' : encounter.elite ? 'ELITE' : 'EXPLORATION') + '</div><h2>Prepare the next experiment.</h2><p>' + encounter.tip + '</p>' + btn('Enter floor ' + run.floor, 'run-battle') + '</section>')
    + '<div class="advanced-formation spaced-heading">' + run.team.map((slot, i) => '<article class="panel content-panel"><h3>' + VESSEL_BY_ID[slot.vessel].name + ' · ' + Math.round(run.health[i] * 100) + '% health</h3><label>Core<select data-run-slot="0" data-index="' + i + '">' + options(run.elements, slot.elements[0]) + '</select></label><label>Secondary<select data-run-slot="1" data-index="' + i + '">' + options(run.elements, slot.elements[1]) + '</select></label></article>').join('') + '</div>'
    + '<section class="panel content-panel spaced-heading"><h2>A traveling laboratory</h2><p>Run discoveries enter your permanent codex when you finish or retire.</p><div class="form-row"><label>First element<select id="run-a">' + options(run.elements) + '</select></label><label>Second element<select id="run-b">' + options(run.elements, run.elements[1]) + '</select></label>' + btn('Experiment', 'run-experiment') + '</div><p>Upgrades: ' + (run.upgrades.map(id => RUN_UPGRADES.find(u => u.id === id).name).join(', ') || 'none yet') + '</p></section><div class="button-row spaced-heading">' + btn('Return with your discoveries', 'retire-run') + '</div>';
}

export async function handleExpansionAction(player, action, target, helpers) {
  const id = target.dataset.id, index = Number(target.dataset.index);
  const value = selector => document.querySelector(selector).value;
  let result;
  switch (action) {
    case 'trial': await helpers.trial(id); return;
    case 'claim-all': case 'craft-all': case 'craft': case 'talent': case 'quest': case 'cosmetic': result = await helpers.command(action, { id }); break;
    case 'evolve': result = await helpers.command('evolve', { id: value('#evolution-element') }); break;
    case 'specialize': result = await helpers.command('specialize', { id: value('#evolution-element'), specialization: value('#specialization') }); break;
    case 'save-loadout': result = await helpers.command(action, { name: value('#loadout-name') }); break;
    case 'apply-loadout': result = await helpers.command(action, { index }); break;
    case 'start-run': { const mode = target.dataset.mode; result = await helpers.command(action, { mode, elements: [...new Set([value('#start-a-' + mode), value('#start-b-' + mode)])] }); break; }
    case 'run-reward': result = await helpers.command(action, { index }); break;
    case 'run-experiment': { const rule = await helpers.command(action, { a: value('#run-a'), b: value('#run-b') }); helpers.toast(rule ? 'Discovered ' + rule.name + ' for this run.' : 'No stable reaction. Try a different pairing.'); helpers.refresh(); return; }
    case 'retire-run': case 'daily': result = await helpers.command(action); break;
    case 'run-battle': await helpers.runBattle(); return;
    default: return;
  }
  helpers.toast(result ? 'Your journal has been updated.' : 'The requirements are not met yet.'); helpers.refresh();
}
